export const ADD_COLLABORATOR = 'ADD_COLLABORATOR';
export const REMOVE_COLLABORATOR = 'REMOVE_COLLABORATOR';
export const UPDATE_COLLABORATOR = 'UPDATE_COLLABORATOR';
export const SET_COLLABORATORS = 'SET_COLLABORATORS';